# Generated by Django 4.2.13 on 2024-06-12 17:24

from django.db import migrations, models
import upload_file.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('year_founded', models.IntegerField(validators=[upload_file.models.valid_year])),
                ('industry', models.CharField(max_length=100)),
                ('size_range', models.IntegerField()),
                ('locality', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('linkedin_url', models.URLField()),
                ('current_employee_estimate', models.IntegerField()),
                ('total_employee_estimate', models.IntegerField()),
            ],
        ),
    ]
