# Generated by Django 4.2.13 on 2024-06-12 17:45

from django.db import migrations, models
import upload_file.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='country',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='current_employee_estimate',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='domain',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='industry',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='linkedin_url',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='locality',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='size_range',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='total_employee_estimate',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='year_founded',
            field=models.IntegerField(default=None, null=True, validators=[upload_file.models.valid_year]),
        ),
    ]
